export default {
  name: "Nabin Karki",
  info: "A senior-year design student who trying to specialize in 3D modeling & texturing.",
  gitLink: "https://github.com/nabin0433",
  linkInLink: "https://www.linkedin.com/in/nabin-karki-18a514204/",
  instaLink: "https://www.instagram.com/nabin0433/",
  gif: ["/assets/images/p-18/gif-1.gif", "/assets/images/p-18/gif-2.gif"],
  project: [
    {
      id: "01",
      name: "Live Video Player",
      img: "https://picsum.photos/500/500",
      alt: "Nabin",
      des: "Goblin concept digital sculpture with human-like skin. Learned a lot of quick tips and look development.",
      info: "Sculpted in ZBrush, Retopologized and UVs done in Maya, Textured in Mari, Rendered using Arnold.",
      linktitle: "More shots from this project ↗",
      link: "/",
    },
    {
      id: "02",
      name: "PDF Viewer",
      img: "https://picsum.photos/400/400",
      alt: "Nabin",
      des: "Goblin concept digital sculpture with human-like skin. Learned a lot of quick tips and look development.",
      info: "Sculpted in ZBrush, Retopologized and UVs done in Maya, Textured in Mari, Rendered using Arnold.",
      linktitle: "More shots from this project ↗",
      link: "/",
    },
    {
      id: "03",
      name: "Junkiri labs",
      img: "https://picsum.photos/600/600",
      alt: "Nabin",
      des: "Goblin concept digital sculpture with human-like skin. Learned a lot of quick tips and look development.",
      info: "Sculpted in ZBrush, Retopologized and UVs done in Maya, Textured in Mari, Rendered using Arnold.",
      linktitle: "See case study →",
      link: "/",
    },
    {
      id: "04",
      name: "Ultimodeal Admin",
      img: "https://picsum.photos/600/640",
      alt: "Nabin",
      des: "Ultimodeal is an E-commerce company based in Kathmandu, Nepal. It was founded by Manish Ghimire in 2017 and is emerging as one of the trusted online shopping sites in Nepal.",
      info: "In November 2020, Ultimodeal raised an undisclosed amount of investment in its Series A funding round[1] led by Venture Capitalist, Social Activist, Actress and Entrepreneur Shweta Khadka[2]. She joined the board of directors as the Chairman of the company.",
      linktitle: "Full Website →",
      link: "https://www.ultimodeal.com.np",
    },
    {
      id: "05",
      name: "Ultimodeal User",
      img: "https://picsum.photos/640/600",
      alt: "Nabin",
      des: "Ultimodeal is an E-commerce company based in Kathmandu, Nepal. It was founded by Manish Ghimire in 2017 and is emerging as one of the trusted online shopping sites in Nepal.",
      info: "In November 2020, Ultimodeal raised an undisclosed amount of investment in its Series A funding round[1] led by Venture Capitalist, Social Activist, Actress and Entrepreneur Shweta Khadka[2]. She joined the board of directors as the Chairman of the company.",
      linktitle: "view Website →",
      link: "https://www.ultimodeal.com.np",
    },
  ],
};
