export default [
  {
    name: "day-1",
    tittle: "portfolio",
    tag: "Completed",
    link: "/p-1/home",
    info: "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet.",
  },
  {
    name: "day-2",
    tittle: "Hospital-Langin_page",
    tag: "Completed",
    link: "/p-2/home",
    info: "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet.",
  },
  {
    name: "day-3",
    tittle: "Food-landing_page",
    tag: "Completed",
    link: "/p-3/home",
    info: "It is a non vegetarian salad which consists of the green goddess dressing mixed with chicken, peppers, olives and celery.",
  },
  {
    name: "day-4",
    tittle: "Landing Page UI KIT",
    tag: "Completed",
    link: "/p-4/home",
    info: "Concise and Compelling Headline (and Subheading) A headline is one of the most important pieces of a perfect landing page,Hero Shot.Identification of Audience Problems,Expression of Your Solutions,List of Features and Benefits,Credentials.",
  },
  {
    name: "day-5",
    tittle: "Registration onboarding design",
    tag: "Completed",
    link: "/p-5/home",
    info: "The onboarding process is essentially a series of screens which direct users through an app interface. These onboarding screens have three purposes: Educate the user about the functions and benefits of the app",
  },
  {
    name: "day-6",
    tittle: "Dark landing page design",
    tag: "Completed",
    link: "/p-6/home",
    info: "Buy dark landing pages & templates from $6. All created by our Global Community of independent Web Designers and Developers.",
  },
  {
    name: "day-7",
    tittle: "IT-Companey-landing-page",
    tag: "Soon ...",
    link: "/p-7/home",
    info: "Something with white background as shown in above two examples + backgro…",
  },
  {
    name: "day-8",
    tittle: "Analytics — landing page design",
    tag: "Completed",
    link: "/p-8/home",
    info: "In Google Analytics, any page can be a landing page. It's simply the first page a visitor goes to on your site, essentially their point of arrival. They might get there from clicking a Google search result",
  },
  {
    name: "day-9",
    tittle: "..",
    tag: "Soon ...",
    link: "/p-9/home",
    info: "...",
  },
  {
    name: "day-10",
    tittle: "....",
    tag: "Soon ...",
    link: "/p-10/home",
    info: "...",
  },
];
