export default [
  {
    name: "day-1",
    tittle: "portfolio",
    tag: "Completed",
    link: "/p-1/home",
    info: "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet.",
  },
  {
    name: "day-2",
    tittle: "Hospital-Langin_page",
    tag: "Completed",
    link: "/p-2/home",
    info: "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet.",
  },
  {
    name: "day-3",
    tittle: "Food-landing_page",
    tag: "Completed",
    link: "/p-3/home",
    info: "It is a non vegetarian salad which consists of the green goddess dressing mixed with chicken, peppers, olives and celery.",
  },
  {
    name: "day-4",
    tittle: "Landing Page UI KIT",
    tag: "Completed",
    link: "/p-4/home",
    info: "Concise and Compelling Headline (and Subheading) A headline is one of the most important pieces of a perfect landing page,Hero Shot.Identification of Audience Problems,Expression of Your Solutions,List of Features and Benefits,Credentials.",
  },
  {
    name: "day-5",
    tittle: "Registration onboarding design",
    tag: "Completed",
    link: "/p-5/home",
    info: "The onboarding process is essentially a series of screens which direct users through an app interface. These onboarding screens have three purposes: Educate the user about the functions and benefits of the app",
  },
  {
    name: "day-6",
    tittle: "Dark landing page design",
    tag: "Completed",
    link: "/p-6/home",
    info: "Buy dark landing pages & templates from $6. All created by our Global Community of independent Web Designers and Developers.",
  },
  {
    name: "day-7",
    tittle: "IT-Companey-landing-page",
    tag: "Soon ...",
    link: "/p-7/home",
    info: "Something with white background as shown in above two examples + backgro…",
  },
  {
    name: "day-8",
    tittle: "Analytics — landing page design",
    tag: "Completed",
    link: "/p-8/home",
    info: "In Google Analytics, any page can be a landing page. It's simply the first page a visitor goes to on your site, essentially their point of arrival. They might get there from clicking a Google search result",
  },
  {
    name: "day-9",
    tittle: "food delivery app",
    tag: "Completed",
    link: "/p-9/home",
    info: "The most widely available food delivery service, active in six continents and first or second in gross orders in most countries",
  },
  {
    name: "day-10",
    tittle: "Squid Game",
    tag: "Completed",
    link: "/p-10/home",
    info: "Squid Game (Korean: 오징어 게임; RR: Ojing-eo Geim) is a South Korean survival drama television series on Netflix created by Hwang Dong-hyuk, who wrote and directed all nine episodes. Its cast includes Lee Jung-jae, Park Hae-soo, Wi Ha-joon, Jung Ho-yeon, O Yeong-su, Heo Sung-tae, Anupam Tripathi, and Kim Joo-ryoung.",
  },
  {
    name: "day-11",
    tittle: "Reality Travel",
    tag: "Completed",
    link: "/p-11/home",
    info: "High-quality photography. A brief summary of the area, with highlights of important places. Hotel recommendations with web links to hotel and booking sites. Information about recreation and outdoor activities.",
  },
  {
    name: "day-12",
    tittle: "Skeleton Login Form",
    tag: "Completed",
    link: "/p-12/home",
    info: "Official Partner for India since 1969, supplies latest Color Shade Cards & manages color trends with best solutions for Textile, Design, Home, Appare",
  },
  {
    name: "day-13",
    tittle: "Product Management",
    tag: "Completed",
    link: "/p-13/home",
    info: "Product management is the job of looking after a specific product within a business. ... That means coming up with a product strategy, thinking about what to build (Product Development), and working out how to market and sell the product (Product Marketing).",
  },
  {
    name: "day-14",
    tittle: "CarVenture",
    tag: "Completed",
    link: "/p-14/home",
    info: "A valid driver's license with a photo. A photo ID (For example: a driver's license or passport) Credit or debit card (check the acceptable forms of payment at the location you're renting from)",
  },
  {
    name: "day-15",
    tittle: "Spotify-clone",
    tag: "Completed",
    link: "/p-15/home",
    info: "(Pocket-lint) - Spotify is a digital music streaming service that gives you access to millions of songs, podcasts and videos from artists all over the world, like Apple Music. ... The free version of Spotify can be accessed on PC, laptop and mobile phone, but the full service needs a Spotify Premium subscription",
  },
  {
    name: "day-16",
    tittle: "Banking App Landing page",
    tag: "Completed",
    link: "/p-16/home",
    info: "Mobile Banking App Landing Page is a responsive landing page template that has been created for presentation of mobile apps and mobile banking.",
  },
  {
    name: "day-17",
    tittle: "Reality Pay",
    tag: "Completed",
    link: "/p-17/home",
    info: "PayRetailers is a payment gateway that supports a wide range of payment methods in LATAM. Accept digital payments on any device and increase your conversion rates. One Payment Platform. PCI DSS Level 1. Best-in-class security. Multi-currency processing.",
  },
  {
    name: "day-18",
    tittle: "Portfolio",
    tag: "Completed",
    link: "/p-18/home",
    info: "A portfolio is a compilation of materials that exemplifies your beliefs, skills, qualifications, education, training and experiences.",
  },
  {
    name: "day-19",
    tittle: "null",
    tag: "Soon..",
    link: "/p-19/home",
    info: "....",
  },
  {
    name: "day-20",
    tittle: "null",
    tag: "Soon..",
    link: "/p-20/home",
    info: "....",
  },
];
